version: '3.3'
services:
  mariadb_master:
    container_name: mariadb_master
    ports:
      - "3306:3306"
    user: root
    image: mariadb:master
 
 
  mariadb_slave:
    container_name: mariadb_slave
    ports:
      - "3307:3306"
    user: root
    image: mariadb:slave

  mycat:
    container_name: mycat
    ports:
      - "8066:8066"
      - "9066:9066"
    user: root
    image: mycat:shop
